{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "c4042c59-b3ac-4709-abe3-189751e19cd8",
   "metadata": {},
   "source": [
    "## Exception handling in Python through try and except\n",
    "\n",
    "### Exception handling in Python is a way to handle unexpected errors or exceptional situations that may occur while your program is running. These errors can be things like dividing by zero, trying to access a file that doesn't exist, or even a simple typo in your code. To handle these situations, Python provides a mechanism called \"try\" and \"except.\"\n",
    "\n",
    "### try block- it executes first and contains statements that may contain error or suspicious to produce an error\n",
    "### except block- it handles error generated by try block\n",
    "### else block- it gets executed when 'try' block executes sucessfully without invoking 'except' block\n",
    "### finally block- it always executed\n",
    "\n",
    "### Note:- We can use any number of try-except cases and even nested ones. "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "89446eed-6798-414a-a8ef-db7f6b6f6ca0",
   "metadata": {},
   "outputs": [],
   "source": [
    "a=3"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "96b57c1c-8409-4dea-88da-a43a98107386",
   "metadata": {},
   "outputs": [
    {
     "ename": "ZeroDivisionError",
     "evalue": "division by zero",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mZeroDivisionError\u001b[0m                         Traceback (most recent call last)",
      "Cell \u001b[0;32mIn[4], line 2\u001b[0m\n\u001b[1;32m      1\u001b[0m \u001b[38;5;66;03m# this will generate an error:- ZeroDivisionError\u001b[39;00m\n\u001b[0;32m----> 2\u001b[0m \u001b[43ma\u001b[49m\u001b[38;5;241;43m/\u001b[39;49m\u001b[38;5;241;43m0\u001b[39;49m\n",
      "\u001b[0;31mZeroDivisionError\u001b[0m: division by zero"
     ]
    }
   ],
   "source": [
    "# this will generate an error:- ZeroDivisionError\n",
    "a/0"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "249e6cb6-f65a-4c54-8d98-0b7545634554",
   "metadata": {},
   "outputs": [
    {
     "name": "stdin",
     "output_type": "stream",
     "text": [
      "Input number 1= 23\n",
      "Input number 2= #\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Enter a valid value\n"
     ]
    }
   ],
   "source": [
    "# to handle this error we'll use try and except\n",
    "try:\n",
    "    num1=int(input('Input number 1='))\n",
    "    num2=int(input('Input number 2='))\n",
    "    num3=num1/num2\n",
    "    print('Num1 when divided by Num2 results in {}'.format(num3))\n",
    "except ZeroDivisionError :\n",
    "    print(\"Division by 0 is not allowed\")\n",
    "except ValueError:\n",
    "    print(\"Enter a valid value\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "id": "f7f16277-fdd4-423f-a42b-8774c08015de",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "There is some problem with that:  [Errno 2] No such file or directory: 'twxt.txt'\n"
     ]
    }
   ],
   "source": [
    "try:\n",
    "    f=open(\"twxt.txt\",'r')\n",
    "except Exception as e:\n",
    "    print(\"There is some problem with that: \",e)\n",
    "    \n",
    "# This will generate an error as we are trying to open a file which does not even exist\n",
    "# 'Exception' is itself a class where 'FileNotFoundError' is its child class"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 18,
   "id": "18d2a0da-0130-4c14-b819-406ef0292864",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "This will execute once 'try' block executes sucessfully\n"
     ]
    }
   ],
   "source": [
    "try:\n",
    "    f=open(\"twext.txt\", 'w')\n",
    "    f.write(\"This is just signalling msg\")\n",
    "except Exception as e:\n",
    "    print(\"There is some problem with code: \",e)\n",
    "else:\n",
    "    f.close()\n",
    "    print(\"This will execute once 'try' block executes sucessfully\")\n",
    "    \n",
    "# this code will create a file named 'twext.txt' and write in it the given message.\n",
    "# and closes ( f.close() ) it in 'else' block.\n",
    "# but for some reason 'try' block genrates an error the file will not be closed as else block will not be executed.\n",
    "# for this case we can use 'finally' block"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 22,
   "id": "538a6efe-a131-49f3-870a-cc9ae7d1ab59",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "This will always be executed whether an error is handled or not \n"
     ]
    },
    {
     "ename": "FileNotFoundError",
     "evalue": "[Errno 2] No such file or directory: 'twxt.txt'",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mFileNotFoundError\u001b[0m                         Traceback (most recent call last)",
      "Cell \u001b[0;32mIn[22], line 2\u001b[0m\n\u001b[1;32m      1\u001b[0m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[0;32m----> 2\u001b[0m     f\u001b[38;5;241m=\u001b[39m\u001b[38;5;28;43mopen\u001b[39;49m\u001b[43m(\u001b[49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[38;5;124;43mtwxt.txt\u001b[39;49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[43m,\u001b[49m\u001b[38;5;124;43m'\u001b[39;49m\u001b[38;5;124;43mr\u001b[39;49m\u001b[38;5;124;43m'\u001b[39;49m\u001b[43m)\u001b[49m\n\u001b[1;32m      3\u001b[0m     f\u001b[38;5;241m.\u001b[39mread()\n\u001b[1;32m      4\u001b[0m \u001b[38;5;28;01mfinally\u001b[39;00m:\n",
      "File \u001b[0;32m/opt/conda/lib/python3.10/site-packages/IPython/core/interactiveshell.py:282\u001b[0m, in \u001b[0;36m_modified_open\u001b[0;34m(file, *args, **kwargs)\u001b[0m\n\u001b[1;32m    275\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m file \u001b[38;5;129;01min\u001b[39;00m {\u001b[38;5;241m0\u001b[39m, \u001b[38;5;241m1\u001b[39m, \u001b[38;5;241m2\u001b[39m}:\n\u001b[1;32m    276\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m \u001b[38;5;167;01mValueError\u001b[39;00m(\n\u001b[1;32m    277\u001b[0m         \u001b[38;5;124mf\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mIPython won\u001b[39m\u001b[38;5;124m'\u001b[39m\u001b[38;5;124mt let you open fd=\u001b[39m\u001b[38;5;132;01m{\u001b[39;00mfile\u001b[38;5;132;01m}\u001b[39;00m\u001b[38;5;124m by default \u001b[39m\u001b[38;5;124m\"\u001b[39m\n\u001b[1;32m    278\u001b[0m         \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mas it is likely to crash IPython. If you know what you are doing, \u001b[39m\u001b[38;5;124m\"\u001b[39m\n\u001b[1;32m    279\u001b[0m         \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124myou can use builtins\u001b[39m\u001b[38;5;124m'\u001b[39m\u001b[38;5;124m open.\u001b[39m\u001b[38;5;124m\"\u001b[39m\n\u001b[1;32m    280\u001b[0m     )\n\u001b[0;32m--> 282\u001b[0m \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[43mio_open\u001b[49m\u001b[43m(\u001b[49m\u001b[43mfile\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;241;43m*\u001b[39;49m\u001b[43margs\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;241;43m*\u001b[39;49m\u001b[38;5;241;43m*\u001b[39;49m\u001b[43mkwargs\u001b[49m\u001b[43m)\u001b[49m\n",
      "\u001b[0;31mFileNotFoundError\u001b[0m: [Errno 2] No such file or directory: 'twxt.txt'"
     ]
    }
   ],
   "source": [
    "try:\n",
    "    f=open(\"twxt.txt\",'r')\n",
    "    f.read()\n",
    "finally:\n",
    "    print(\"This will always be executed whether an error is handled or not \")"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "35fb75ea-0c62-4479-a791-14fee5f7693e",
   "metadata": {},
   "source": [
    "### The purpose of the \"finally\" block is to ensure that certain cleanup or finalization tasks are performed, no matter what happens within the \"try\" block. It's commonly used for activities like closing files, releasing resources, or performing cleanup operations."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "ae1db4e4-c844-45ac-864f-9f01042a7bf8",
   "metadata": {},
   "source": [
    "## CUSTOM EXCEPTION HANDLING"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "4ff5aa37-ceaa-4677-add5-f6dfaa803320",
   "metadata": {},
   "outputs": [
    {
     "name": "stdin",
     "output_type": "stream",
     "text": [
      "Enter your age =  -90\n"
     ]
    }
   ],
   "source": [
    "age=int(input(\"Enter your age = \"))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "8de7278f-ffe3-4f98-bbdb-4de970a97344",
   "metadata": {},
   "outputs": [],
   "source": [
    "# As we know age can't be negative but for the computer it is a valid integer, so it accepts it without any problem.\n",
    "# to deals with such type of issues we can use 'Custom Exception Handling'\n",
    "pass"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "1276e6f9-1cfa-401d-a0ac-46d5a49b383f",
   "metadata": {},
   "outputs": [],
   "source": [
    "class validateage(Exception):\n",
    "    def __init__(self,msg):\n",
    "        self.msg=msg\n",
    "\n",
    "# inherting Exception class in it."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "39e7afc7-7c42-4474-b9b8-20da6d6cd8a1",
   "metadata": {},
   "outputs": [],
   "source": [
    "def validate_age(age):\n",
    "    if age<0:\n",
    "        raise validateage(\"Age should be greater than 0\")\n",
    "    elif age>170:\n",
    "        raise validateage(\"Age is too high\")\n",
    "    else:\n",
    "        print(\"Age recorded\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "id": "7ac54ddd-67fa-40ff-b6ec-db46fb1bad2f",
   "metadata": {},
   "outputs": [
    {
     "name": "stdin",
     "output_type": "stream",
     "text": [
      "Enter age =  ert\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "There is some problem :  invalid literal for int() with base 10: 'ert'\n"
     ]
    }
   ],
   "source": [
    "try:\n",
    "    age=int(input(\"Enter age = \"))\n",
    "    validate_age(age)\n",
    "except validateage as e:\n",
    "    print(e)\n",
    "except ValueError as e:\n",
    "    print(f\"There is some problem : \",e)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "3a68807a-3881-41a0-b14f-a27998af28e8",
   "metadata": {},
   "source": [
    "## List of genral use Exception"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "id": "06926784-b500-4247-81cb-7ce8534e257d",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "You divided by zero, didn't you? Nice one!\n"
     ]
    }
   ],
   "source": [
    "try:\n",
    "    # Your risky code goes here\n",
    "    result = 10 / 0\n",
    "except ZeroDivisionError:\n",
    "    # Handle the exception here, like a pro\n",
    "    print(\"You divided by zero, didn't you? Nice one!\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "8cbd61e9-ad26-4cee-942f-8e27b6949102",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "You serious? Really? : invalid literal for int() with base 10: 'tan'\n"
     ]
    }
   ],
   "source": [
    "try:\n",
    "    int(\"tan\")\n",
    "except (ValueError,TypeError) as e:\n",
    "    print(\"You serious? Really? :\",e)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "4aa1e9df-62db-4c4f-88e1-f93735a11f1b",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "No module named 'msgg'\n"
     ]
    }
   ],
   "source": [
    "try:\n",
    "    import msgg\n",
    "except ImportError as e:\n",
    "    print(e)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "62f335da-49d1-48e8-a192-90f03e4d513f",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "'Key4'\n"
     ]
    }
   ],
   "source": [
    "try:\n",
    "    di={ 1:(9,8,7) , \"Key1\":(6,5,4)}\n",
    "    di[\"Key4\"]\n",
    "except KeyError as e:\n",
    "    print(e)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "e862bf2b-ff22-4d68-8741-b150ef353570",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "'str' object has no attribute 'textt'\n"
     ]
    }
   ],
   "source": [
    "try:\n",
    "    \"tan\".textt()\n",
    "except AttributeError as e:\n",
    "    print(e)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "b2b09bdf-a231-4b75-a9b7-6f5cd7fde2f3",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "list index out of range\n"
     ]
    }
   ],
   "source": [
    "try:\n",
    "    l=[1,2,3,4,5]\n",
    "    l[8]\n",
    "except IndexError as e:\n",
    "    print(e)    "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "2786135c-4858-4280-86d6-530a86fb699f",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "unsupported operand type(s) for +: 'int' and 'str'\n"
     ]
    }
   ],
   "source": [
    "try:\n",
    "    12+\"ERR\"\n",
    "except TypeError as e:\n",
    "    print(e)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "id": "884dc452-506b-4c3d-a09c-221a3775c9e2",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[Errno 2] No such file or directory: 'ret.txt'\n"
     ]
    }
   ],
   "source": [
    "try:\n",
    "    with open(\"ret.txt\",'r') as f:\n",
    "        f.read()\n",
    "except FileNotFoundError as e:\n",
    "    print(e)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "id": "a359b46b-cac3-4754-8602-dfd77d896688",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "there is some problem occoured\n"
     ]
    }
   ],
   "source": [
    "# except will itself call error superclass\n",
    "# this is Not a good practice. Always try to specify error class.\n",
    "try:\n",
    "    10/0\n",
    "except:\n",
    "    print(\"there is some problem occoured\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 18,
   "id": "471eb193-d518-4d99-8c2d-bfdc52af602f",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error detected as : [Errno 2] No such file or directory: 'ret.txt'\n"
     ]
    }
   ],
   "source": [
    "try:\n",
    "    with open(\"ret.txt\",'r') as f:\n",
    "        f.read()\n",
    "        \n",
    "except Exception as e:\n",
    "    print(f\"Error detected as : {e}\" )\n",
    "\n",
    "except FileNotFoundError as e:       # this will not be executed as the super class is called before it. \n",
    "    print(f\"Error found as : {e}\")\n",
    "    \n",
    "# this is NOT a good practice. Always try to add error superclass at the end after defining all possible error types."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 19,
   "id": "cfa214e5-f7c1-45b0-8b24-29465b2823fd",
   "metadata": {},
   "outputs": [],
   "source": [
    "# how to log errors\n",
    "# and perform cleanup. Closing the file.\n",
    "\n",
    "import logging\n",
    "logging.basicConfig(filename='ErrorInfo.log', level=logging.ERROR)\n",
    "\n",
    "try:\n",
    "    with open(\"New_Test.txt\",'w') as f:\n",
    "        f.write(\"This will be going to file. And its gone already! \")\n",
    "\n",
    "except FileNotFoundError as e:\n",
    "    logging.error(\"Error Found : {}\".format(e))\n",
    "\n",
    "finally:\n",
    "    f.close()"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.8"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
